### PR TITLE
Karls fixes

### PR DESCRIPTION
**Pull request by karlscheib**
started on 5 and 6. got images for each game and included them as components of GAMES in games.js (I hope that makes sense)

### CODE REVIEW

**Comment by karlscheib** [comment]
this is not ready for merge yet

**Comment by kudlakk** [comment]
> this is not ready for merge yet

Sounds good, thanks for the update. I would recommend pointing the PR to the branch that it is most up to date with (ColorGame?) instead of pointing it at main

**Comment by kudlakk** [comment]
Also, I like the images you have 👍

**Comment by karlscheib** [comment]
Not sure what you mean by "pointing". If it isnt too complicated I could change where it points to.

**Comment by kudlakk** [comment]
> Not sure what you mean by "pointing". If it isnt too complicated I could change where it points to.

it isn't a major deal so if it's too hard to conceptualize then don't worry about it

by "pointing", I mean set your PR to merge into the branch "ColorGame" (or whatever branch it's most up to date with) instead of "main". Doing so will prevent changes that aren't a part of this PR from being reflected on main. 

In other words, your PR has changes that are not *just* part of this PR. It also has ColorGame changes because you merged those into this branch. This PR should not merge into main until after ColorGame merges into main. Instead of setting your PR to merge into main, set it to merge into ColorGame. Doing so will also make the dif more clear so it's easier to see which changes are specific to this PR

**Pull request closed without merging**
